# Generated by Django 4.0.3 on 2022-12-05 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogx_delete_blogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogx',
            new_name='Blogs',
        ),
    ]
