# Generated by Django 4.0.3 on 2022-12-05 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_s_delete_blogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_s',
            new_name='Jobs',
        ),
    ]
